apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: surfza-com-tls
spec:
  secretName: surfza-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: surfza.com
  dnsNames:
    - surfza.com
    - www.surfza.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - surfza.com
          - www.surfza.com